version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ../.env.example
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"

volumes:
  mongo-data:
